apiVersion: v1
kind: Service
metadata:
  name: my-service-a
spec:
  clusterIP: None
  selector:
    app: my-service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-a-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-service-a
  template:
    metadata:
      labels:
        app: my-service-a
    spec:
      containers:
        - name: my-container
          image: my-service-a-image
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-service-b
spec:
  clusterIP: None
  selector:
    app: my-service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-service-b-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-service-b
  template:
    metadata:
      labels:
        app: my-service-b
    spec:
      containers:
        - name: my-container
          image: my-service-b-image
          ports:
            - containerPort: 8080