apiVersion: apps/v1
kind: Deployment
metadata:
  name: teg-app
  namespace: production
spec:
  replicas: 6
  selector:
    matchLabels:
      app: teg
  template:
    metadata:
      labels:
        app: teg
    spec:
      containers:
      - name: teg-container
        image: teg-app:v1.0